### ISSUE TITLE
Compilation error, go 1.6.2 linux/amd64 Ubuntu 16.04

### ISSUE THREAD

**Issue by AlbertoGP** [dubyte/dir2opds#1]
Hi, just tried installing dir2opds: (XXX/go is $GOPATH)

```sh
~$ go get github.com/dubyte/dir2opds
# github.com/dubyte/dir2opds
XXX/go/src/github.com/dubyte/dir2opds/main.go:158: undefined: url.PathEscape
~$ go version
go version go1.6.2 linux/amd64
```

I haven't written any go code ever, but if you can't reproduce this I'm ready to spend a little time trying out your suggestions.

**Comment by dubyte** [comment]
Hi Albert:

I confirm that this happen, the problem is because url.PathEscape was introduce in go 1.7 for the moment I don't plan tu support 1.6 compilation. But since you dont program in go.
What do you think about a binay relese?
that you can download here: https://github.com/dubyte/dir2opds/releases/download/v0.0.2/dir2opds_0.0.2_Linux-64bit.tar.gz

Sorry for this.
